"""empty message

Revision ID: 1da4e44be7ce
Revises: 68fb0dc90ad2
Create Date: 2025-03-30 11:04:06.426409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da4e44be7ce'
down_revision: Union[str, None] = '68fb0dc90ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_configs',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('punctuation', sa.Boolean(), nullable=True),
    sa.Column('textType', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts',
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['text_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_results',
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_timings',
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_result_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_result_id'], ['text_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_timings')
    op.drop_table('text_results')
    op.drop_table('texts')
    op.drop_table('text_configs')
    # ### end Alembic commands ###
