"""empty message

Revision ID: 44262963bd40
Revises: 551c7ac3776d
Create Date: 2025-03-19 16:11:04.759214

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44262963bd40"
down_revision: Union[str, None] = "551c7ac3776d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("description", sa.String(), nullable=True))
    op.add_column("lessons", sa.Column("text", sa.String(), nullable=True))
    op.add_column("lessons", sa.Column("timing", sa.Integer(), nullable=True))
    op.add_column("lessons", sa.Column("percentage", sa.Integer(), nullable=True))
    op.add_column("lessons", sa.Column("language", sa.String(), nullable=True))
    op.add_column("lessons", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "status")
    op.drop_column("lessons", "language")
    op.drop_column("lessons", "percentage")
    op.drop_column("lessons", "timing")
    op.drop_column("lessons", "text")
    op.drop_column("lessons", "description")
    # ### end Alembic commands ###
