"""empty message

Revision ID: 9e6d0ea78eba
Revises: b6ed9f30434c
Create Date: 2025-03-27 12:37:44.857977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e6d0ea78eba"
down_revision: Union[str, None] = "b6ed9f30434c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lesson_step_results", sa.Column("wpm", sa.Integer(), nullable=True))
    op.add_column(
        "lesson_step_timings", sa.Column("seconds", sa.Integer(), nullable=True)
    )
    op.add_column(
        "lesson_step_timings",
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("lesson_step_timings", "date")
    op.drop_column("lesson_step_timings", "time")
    op.drop_column("lesson_step_timings", "level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lesson_step_timings",
        sa.Column("level", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "lesson_step_timings",
        sa.Column("time", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "lesson_step_timings",
        sa.Column("date", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("lesson_step_timings", "created_date")
    op.drop_column("lesson_step_timings", "seconds")
    op.drop_column("lesson_step_results", "wpm")
    # ### end Alembic commands ###
