"""empty message

Revision ID: e2cda074a401
Revises: 1131c7a10cb4
Create Date: 2025-03-29 11:14:46.063480

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2cda074a401"
down_revision: Union[str, None] = "1131c7a10cb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lesson_step_texts", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lesson_step_texts", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
