version: '3.9'
name: normalizer-test

services:
  test:
      build: 
        context: .
        dockerfile: ./docker/Dockerfile
        target: test
      
      command: >
        bash -c "python -m src.migrate 
        && coverage run --rcfile ./pyproject.toml -m pytest ./tests"
      volumes:
        - ./src/:/usr/src/app/
      env_file: 
        - .env.test

      networks: 
        app-network:
        
  lint:
      build: 
          context: .
          dockerfile: ./docker/Dockerfile
          target: lint
      command: >
        bash -c "black --config ./pyproject.toml --check src tests &&
        isort . --settings-path ./pyproject.toml --check-only &&
        flake8 -q ./src 
        "
     
      volumes:
        - ./src/:/usr/src/app/
      env_file: 
        - .env.test



networks:
  app-network: